#define StringLiteralX(s) {sizeof(s)-1, (u8*)(s)}
String OSKeyStringTable[92] = {
  StringLiteralX("Null"),
  StringLiteralX("Escape"),
  StringLiteralX("F1"),
  StringLiteralX("F2"),
  StringLiteralX("F3"),
  StringLiteralX("F4"),
  StringLiteralX("F5"),
  StringLiteralX("F6"),
  StringLiteralX("F7"),
  StringLiteralX("F8"),
  StringLiteralX("F9"),
  StringLiteralX("F10"),
  StringLiteralX("F11"),
  StringLiteralX("F12"),
  StringLiteralX("F13"),
  StringLiteralX("F14"),
  StringLiteralX("F15"),
  StringLiteralX("F16"),
  StringLiteralX("F17"),
  StringLiteralX("F18"),
  StringLiteralX("F19"),
  StringLiteralX("F20"),
  StringLiteralX("F21"),
  StringLiteralX("F22"),
  StringLiteralX("F23"),
  StringLiteralX("F24"),
  StringLiteralX("Grave Accent"),
  StringLiteralX("0"),
  StringLiteralX("1"),
  StringLiteralX("2"),
  StringLiteralX("3"),
  StringLiteralX("4"),
  StringLiteralX("5"),
  StringLiteralX("6"),
  StringLiteralX("7"),
  StringLiteralX("8"),
  StringLiteralX("9"),
  StringLiteralX("Minus"),
  StringLiteralX("Equal"),
  StringLiteralX("Backspace"),
  StringLiteralX("Delete"),
  StringLiteralX("Tab"),
  StringLiteralX("A"),
  StringLiteralX("B"),
  StringLiteralX("C"),
  StringLiteralX("D"),
  StringLiteralX("E"),
  StringLiteralX("F"),
  StringLiteralX("G"),
  StringLiteralX("H"),
  StringLiteralX("I"),
  StringLiteralX("J"),
  StringLiteralX("K"),
  StringLiteralX("L"),
  StringLiteralX("M"),
  StringLiteralX("N"),
  StringLiteralX("O"),
  StringLiteralX("P"),
  StringLiteralX("Q"),
  StringLiteralX("R"),
  StringLiteralX("S"),
  StringLiteralX("T"),
  StringLiteralX("U"),
  StringLiteralX("V"),
  StringLiteralX("W"),
  StringLiteralX("X"),
  StringLiteralX("Y"),
  StringLiteralX("Z"),
  StringLiteralX("Space"),
  StringLiteralX("Enter"),
  StringLiteralX("Ctrl"),
  StringLiteralX("Shift"),
  StringLiteralX("Alt"),
  StringLiteralX("Up"),
  StringLiteralX("Left"),
  StringLiteralX("Down"),
  StringLiteralX("Right"),
  StringLiteralX("Page Up"),
  StringLiteralX("Page Down"),
  StringLiteralX("Home"),
  StringLiteralX("End"),
  StringLiteralX("Forward Slash"),
  StringLiteralX("Period"),
  StringLiteralX("Comma"),
  StringLiteralX("Quote"),
  StringLiteralX("Left Bracket"),
  StringLiteralX("Right Bracket"),
  StringLiteralX("Insert"),
  StringLiteralX("Left Mouse Button"),
  StringLiteralX("Middle Mouse Button"),
  StringLiteralX("Right Mouse Button"),
  StringLiteralX("Semicolon"),
};
